FROM leochan007/ubuntu1604_base

LABEL MAINTAINER leo chan <leochan007@163.com>

RUN apt-get update && apt-get install -y apache2 php php-curl php-gd php-ldap php-mbstring \
  php-mcrypt php-mysql php-xml php-zip php-cli php-json curl unzip libapache2-mod-php locales

ENV LANG="en_US.UTF8"
RUN echo -e "LANG=\"en_US.UTF-8\"\nLANGUAGE=\"en_US:en\"" > /etc/default/locale && locale-gen en_US.UTF-8

#curl -O http://cdn.zentaopm.com/latest/zentao.zip
RUN mkdir -p /app/zentaopms
COPY docker-entrypoint-o.sh /app
RUN a2enmod rewrite

RUN rm -rf /etc/apache2/sites-enabled/000-default.conf
COPY config/apache.conf /etc/apache2/sites-enabled/000-default.conf
COPY config/ioncube_loader_lin_7.0.so /usr/lib/php/20151012/ioncube_loader_lin_7.0.so
COPY config/00-ioncube.ini /etc/php/7.0/apache2/conf.d/
COPY config/00-ioncube.ini /etc/php/7.0/cli/conf.d/

#VOLUME /app/zentaopms
ENTRYPOINT ["/app/docker-entrypoint-o.sh"]
