FROM php:7.1.25-apache

LABEL MAINTAINER leo chan <leochan007@163.com>

ENV DEBIAN_FRONTEND noninteractive

ENV ZENTAO_VER=10.6

ARG ZENTAO_URL=http://dl.cnezsoft.com/zentao/${ZENTAO_VER}/ZenTaoPMS.${ZENTAO_VER}.stable.zbox_64.tar.gz

RUN apt-get update

RUN apt-get install -y vim telnet unzip

WORKDIR /var/www/html

RUN curl -O ${ZENTAO_URL}

RUN tar -xvf ZenTaoPMS.${ZENTAO_VER}.stable.zbox_64.tar.gz

RUN mv zbox/app/zentao .

#RUN rm -rf zbox/
